name: Ali
age: 28
address: "heuaheua"
active: "true"
key:
  key: value
  key2: 33
  key3: 
   key: value
jsonObject: { key: value, key2: 33, key3: {}}
array:
  - item1
  - item2
  - {key: value}
objectArray:
  - key: value
    key2: value2
  - key: value
    key2: value2

longText: >
  eaeasdasda  dsadsddas
  dasdasd asdadas
  asdas adsad
      