#Workflow
#  -> ref: https://medium.com/google-developer-experts/github-actions-for-android-developers-6b54c8a32f55
name: Build

on:
  push:
#  pull_request:
#    branches:
#      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      ## Checkout ###
      - name: Checkout
        uses: actions/checkout@v3

      ## Setup ###
      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        with:
          arguments: assembleRelease

      # ref: https://github.com/marketplace/actions/setup-android-sdk-tools
      #- name: Setup Android SDK
      #  uses: android-actions/setup-android@v2

      ## Execute ###
      - name: Execute Gradle build
        run: ./gradlew assemble

      ## Tests ###
      - name: Run Unit Tests
        run: ./gradlew test --stacktrace

      ## Formatter ###
      - name: Run Kotlin Linter
        run: ./gradlew ktlint